<?php

namespace L0n3ly\LaravelDynamicHelpers;

use Illuminate\Support\ServiceProvider;
use Illuminate\Support\Str;
use L0n3ly\LaravelDynamicHelpers\Console\MakeHelperCommand;

class HelperServiceProvider extends ServiceProvider
{
    public function register()
    {
        require_once __DIR__.'/../helpers.php';
    }

    public function boot()
    {
        $this->ensureGitignoreEntries();

        $helpers = $this->registerDynamicHelpers();
        $this->generateIdeHelperFile($helpers);
        $this->generatePhpstormMeta($helpers);

        if ($this->app->runningInConsole()) {
            $this->commands([
                MakeHelperCommand::class,
            ]);
        }
    }

    protected function registerDynamicHelpers(): array
    {
        $helpersPath = app_path('Helpers');
        $helpers = [];

        if (! is_dir($helpersPath)) {
            return $helpers;
        }

        $iterator = new \RecursiveIteratorIterator(
            new \RecursiveDirectoryIterator($helpersPath, \RecursiveDirectoryIterator::SKIP_DOTS)
        );

        foreach ($iterator as $file) {
            if (! $file->isFile() || $file->getExtension() !== 'php') {
                continue;
            }

            $relativePath = str_replace($helpersPath.'/', '', $file->getPathname());
            $relativePath = str_replace('.php', '', $relativePath);

            $parts = explode('/', $relativePath);
            $functionName = Str::camel(implode('', $parts));
            $fullClass = 'App\\Helpers\\'.str_replace('/', '\\', $relativePath);

            if (class_exists($fullClass) && ! function_exists($functionName)) {
                eval("function {$functionName}(): \\{$fullClass} { return helpers()->{$functionName}(); }");
                $helpers[$functionName] = $fullClass;
            }
        }

        return $helpers;
    }

    protected function generateIdeHelperFile(array $helpers): void
    {
        if (empty($helpers)) {
            return;
        }

        $helperPath = base_path('_ide_helper.php');
        $stubs = '';

        foreach ($helpers as $functionName => $className) {
            $stubs .= "function {$functionName}(): \\{$className} {}\n";
        }

        $content = <<<'PHP'
<?php

// Auto-generated by laravel-dynamic-helpers
// This file provides IDE type hints for dynamically created helper functions
// Do not edit manually — it will be regenerated on every application boot

PHP;

        $content .= $stubs;

        file_put_contents($helperPath, $content);
    }

    protected function generatePhpstormMeta(array $helpers): void
    {
        if (empty($helpers)) {
            return;
        }

        $metaPath = base_path('.phpstorm.meta.php');
        $overrides = '';

        foreach ($helpers as $functionName => $className) {
            $overrides .= "    \\override(\\{$functionName}(), type(\\{$className}::class));\n";
        }

        $content = <<<'PHP'
<?php

// Auto-generated by laravel-dynamic-helpers
// This file provides IDE type hints for dynamically created helper functions
// Do not edit manually — it will be regenerated on every application boot

namespace {
    class_alias(\L0n3ly\LaravelDynamicHelpers\Helper::class, 'helpers');
}

namespace PHPSTORM_META {
    override(\helpers(), type(\L0n3ly\LaravelDynamicHelpers\Helper::class));
PHP;

        $content .= "\n" . $overrides . "}\n";

        file_put_contents($metaPath, $content);
    }

    protected function ensureGitignoreEntries(): void
    {
        $gitignorePath = base_path('.gitignore');

        if (! file_exists($gitignorePath) || ! is_writable($gitignorePath)) {
            return;
        }

        $gitignoreContent = file_get_contents($gitignorePath) ?: '';
        $entriesToAdd = ['_ide_helper.php', '.phpstorm.meta.php'];
        $lines = array_filter(array_map('trim', explode("\n", $gitignoreContent)), fn($line) => !empty($line));
        $needsUpdate = false;

        foreach ($entriesToAdd as $entry) {
            if (! in_array($entry, $lines, true)) {
                $lines[] = $entry;
                $needsUpdate = true;
            }
        }

        if ($needsUpdate) {
            $content = implode("\n", $lines) . "\n";
            file_put_contents($gitignorePath, $content);
        }
    }

}
