<?php

namespace L0n3ly\LaravelDynamicHelpers\Console;

use Illuminate\Console\Command;
use Illuminate\Support\Str;

class GenerateIdeHelperCommand extends Command
{
    protected $signature = 'helpers:ide {--output=_ide_helper_helpers.php : Output file path relative to base path}';

    protected $description = 'Generate an IDE helper file for dynamic helper autocompletion';

    public function handle()
    {
        $helpersPath = app_path('Helpers');

        if (! is_dir($helpersPath)) {
            $this->components->warn('No app/Helpers directory found. Create helpers first using make:helper.');

            return Command::FAILURE;
        }

        $methods = $this->collectMethods($helpersPath);

        if (empty($methods)) {
            $this->components->warn('No helper classes found in app/Helpers.');

            return Command::FAILURE;
        }

        $outputPath = base_path($this->option('output'));
        $this->writeIdeHelperFile($outputPath, $methods);

        $relativePath = str_replace(base_path().'/', '', $outputPath);
        $this->components->info("IDE helper file generated: [{$relativePath}] with ".count($methods).' helper(s).');

        return Command::SUCCESS;
    }

    protected function collectMethods(string $helpersPath): array
    {
        $methods = [];

        $iterator = new \RecursiveIteratorIterator(
            new \RecursiveDirectoryIterator($helpersPath, \RecursiveDirectoryIterator::SKIP_DOTS)
        );

        foreach ($iterator as $file) {
            if (! $file->isFile() || $file->getExtension() !== 'php') {
                continue;
            }

            $relativePath = str_replace($helpersPath.'/', '', $file->getPathname());
            $relativePath = str_replace('.php', '', $relativePath);

            $parts = explode('/', $relativePath);
            $className = array_pop($parts);
            $namespaceParts = $parts;

            $fqcn = 'App\\Helpers';
            if (! empty($namespaceParts)) {
                $fqcn .= '\\'.implode('\\', $namespaceParts);
            }
            $fqcn .= '\\'.$className;

            $methodName = Str::camel(implode('', $namespaceParts).$className);

            $methods[] = [
                'method' => $methodName,
                'return' => $fqcn,
            ];
        }

        usort($methods, fn ($a, $b) => strcmp($a['method'], $b['method']));

        return $methods;
    }

    protected function writeIdeHelperFile(string $outputPath, array $methods): void
    {
        $docLines = array_map(
            fn ($m) => " * @method \\{$m['return']} {$m['method']}()",
            $methods
        );

        $docBlock = implode("\n", $docLines);

        $content = <<<PHP
<?php

// This file is auto-generated by `php artisan helpers:ide` for IDE autocompletion support.
// Do not edit manually — re-run the command after adding or removing helpers.

namespace L0n3ly\LaravelDynamicHelpers {
    /**
{$docBlock}
     */
    class Helper {}
}
PHP;

        file_put_contents($outputPath, $content."\n");
    }
}
